### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by tyl924** [cicec/we-mobx#1]
第一,按照你的例子使用,报错.  provider & inject模式
```
import { inject } from 'we-mobx'

inject<Stores>('storeA', 'storeB')(({ storeA }) =>
  observer.page({
    ...
  })
)
```
这个能通过使用
但是你下面的例子,还是老版本?

第二,虽然运行起来了,但是执行了定义的action test方法,还是没有执行setdata
检查了 console.log(getApp().stores); 有值
```
  @action
  test(){
    this.allCount = 10;
  }
```
界面不还是不更新... 一开始,appdata 里,只有一个 class 的空对象...
不知道我到底哪里出了错误

第三,调试相当不方便,也许是用ts 编译的原因,如果有两个版本就好了,min js和format js版本,根据环境判断输出哪个,wx工具调试起来,真的非常的头疼.

最后,一年都没更新了,是否还在呢?谢谢

**Comment by cicec** [comment]
抱歉没能及时回复，如果您还在关注的话

1. 文档错误，已更正
2. 请确保通过 inject 显式传入 store 的 name，可以的话请提供可复现代码片段
3. 当前构建版本未包含 sourcemap 文件， 有需要的话会发布一个修复版本添加
